renzuzu/renzu_garage

- renzu_garage/client/client.lua
> tweak dist

- renzu_garage/client/client.lua
Re Open UI if vehicle is just stored or the UI  Just Closed
> tweak(reopenui)

- renzu_garage/html/script.js
- renzu_garage/server/server.lua
fix sql order error if you dont have id column.
fix start up js error
> fix(sql order error)

- renzu_garage/client/client.lua
- renzu_garage/config.lua
- renzu_garage/server/server.lua
enable you to config if you want to use impound and heli garage
> feat(impound&heli config)

- renzu_garage/client/client.lua
- renzu_garage/config.lua
- renzu_garage/server/server.lua
Config.ReturnPayment
to set a price for return vehicle
> feat(returnPayment, faster switching vehicle pages inside garage)

- renzu_garage/server/server.lua
> tweak(uppercase p2)

- renzu_garage/client/client.lua
- renzu_garage/config.lua
- renzu_garage/server/server.lua
configured public parking can be edit at config.
Location size is important.
> feat(realistic park)

- renzu_garage/client/client.lua
to avoid waiting on while loop, ex. same distance to nearby garage
> tweak(realpark self thread)

- renzu_garage/client/client.lua
- renzu_garage/config.lua
- renzu_garage/garage.sql
- renzu_garage/server/server.lua
Sample config is included
SQL is updated
> feat(client/server/sql): Support Boat,Plane Garage.

- renzu_garage/client/client.lua
avoid boat and plane showing up in your garage shell :airplane:
> fix(client): filter car type garage per garage shell

- client/client.lua
Reverts renzuzu/renzu_garage#103
no i forget its vec3
> Revert "Revert "optimisation""

- html/index.html
Minor tweaks that I recommend adding to all your projects - adding defer or async tags to script tags in HTML. It's complicated to explain over text, but you can see from this video the difference in script loading times on a html page when making use of async or defer:
https://www.youtube.com/watch?v=BMuFBYw91UQ - What Is The Fastest Way To Load JavaScript
https://stackoverflow.com/questions/10808109/script-tag-async-defer - Text Reference
> async & defer optimizations

- html/index.html
Reverts renzuzu/renzu_garage#119
this affects some users including me by a chance that the jquery will not load before the script.js 
causing errors.
and this is not needed in fivem UI scripts less effects (only loaded once),
this is only neccessary in websites thats keeps loading a (pages) for headers part.
> Revert "async & defer optimizations"

- server/server.lua
https://github.com/renzuzu/renzu_garage/issues/126
> fix(server): garage inventory bug when shared

- client/client.lua
https://github.com/renzuzu/renzu_garage/issues/134
> fix(client): parkingmeter deletion sync

- client/client.lua
avoid the system to delete the same vehicle patrol car
> tweak(client): job default vehicle Unique Plate

- client/client.lua
- server/server.lua
https://forum.cfx.re/t/release-renzu-garage-public-private-realistic-and-housing-parking-w-garage-inventory-v1-5/3962173/391?u=renzuzu
https://github.com/renzuzu/renzu_garage/issues/154
> fix(client): fix inside garage takeout vehicle and empty garage issue

- html/script.js
See image
https://cdn.discordapp.com/attachments/905458031482011672/905458061362212864/unknown.png
> Updated keys UI to match keys update

- conf/impound.lua
Change blips to tow_truck 
blip id: 68 
color id: 6
> Better blips

- fxmanifest.lua
Update fxmanifest.lua renzu_shield not found
> Update fxmanifest.lua renzu_shield not found

- client/client.lua
Update client.lua fix NUI warnings
(needs testing)
> Update client.lua fix NUI warnings
